### ISSUE TITLE
v0.10.0 possible regression: TypeError: connector.update is not a function

### ISSUE THREAD

**Issue by pozil** [salesforce/sfdx-lwc-jest#172]
### Description

We're seeing possible regressions after updating to v0.10.0. Our CI is reporting [new errors](https://github.com/trailheadapps/ebikes-lwc/pull/223/checks?check_run_id=1121910129).
I'm also able to reproduce locally.

#### Steps to Reproduce

Run these commands:

```bash
git clone git@github.com:trailheadapps/ebikes-lwc.git
git checkout pozil/devDependencies
cd ebikes-lwc
npm install
npm run test:unit
```

#### Expected Results

All tests pass (as before the sfdx-lwc-jest update).

#### Actual Results

Tests are now failing due to internal errors like this one:

```
TypeError: connector.update is not a function

      61 |                 mockGetProducts.totalItemCount / mockGetProducts.pageSize
      62 |             );
    > 63 |             const element = createElement('c-product-tile-list', {
         |                             ^
      64 |                 is: ProductTileList
      65 |             });
      66 |             document.body.appendChild(element);

      at node_modules/@lwc/engine/dist/engine.cjs.js:6606:17
      at runWithBoundaryProtection (node_modules/@lwc/engine/dist/engine.cjs.js:6410:5)
      at updateConnectorConfig (node_modules/@lwc/engine/dist/engine.cjs.js:6604:5)
      at computeConfigAndUpdate (node_modules/@lwc/engine/dist/engine.cjs.js:6614:5)
      at createConnector (node_modules/@lwc/engine/dist/engine.cjs.js:6625:5)
      at installWireAdapters (node_modules/@lwc/engine/dist/engine.cjs.js:6701:31)
      at createVM (node_modules/@lwc/engine/dist/engine.cjs.js:6006:5)
      at createElement (node_modules/@lwc/engine/dist/engine.cjs.js:7071:5)
      at Object.<anonymous> (force-app/main/default/lwc/productTileList/__tests__/productTileList.test.js:63:29)
```

### Version

-   @salesforce/sfdx-lwc-jest: 0.10.0
-   Node: 10.16.3

**Comment by jodarove** [comment]
@pozil v0.10.1 should fix your issues. pls confirm.

**Comment by pozil** [comment]
Thanks for the quick update @jodarove.
I confirm that the issue is fixed in the new version.
