### ISSUE TITLE
Connector.connect is not a function

### ISSUE THREAD

**Issue by gdlt88** [salesforce/sfdx-lwc-jest#246]
### Description
We are trying to use flows in our apex classes and in order to do that we need to upgrade our sourceApiVersion. Updating the sourceApiVersion means updating @salesforce/sfdx-lwc-jest. After updating @salesforce/sfdx-lwc-jest to latest, we are seeing the following error:

```
    TypeError: connector.connect is not a function

       5 |     const element = createElement(name, { is: constructor });
       6 |     Object.keys(attrs).forEach((key) => (element[key] = attrs[key]));
    >  7 |     document.body.appendChild(element);
         |     ^
       8 |     Object.keys(attrs)
       9 |       .filter((key) => key.startsWith("on"))
      10 |       .forEach((key) => element.addEventListener(key.substr(2), attrs[key]));

      at Array.<anonymous> (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:7477:19)
      at connectWireAdapters (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:7498:23)
      at runConnectedCallback (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:6927:5)
      at connectRootElement (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:6630:3)
      at callNodeSlot (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:7838:9)
      at HTMLBodyElement.document [as appendChild] (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:7848:16)
```

Our test classes work with version 0.9.2 without any issues.

#### Steps to Reproduce

Our utils.js  class
```
import { createElement } from "lwc";

export function buildSubject(name, constructor, defaults = {}) {
  return function (attrs = defaults) {
    const element = createElement(name, { is: constructor });
    Object.keys(attrs).forEach((key) => (element[key] = attrs[key]));
    document.body.appendChild(element);
    Object.keys(attrs)
      .filter((key) => key.startsWith("on"))
      .forEach((key) => element.addEventListener(key.substr(2), attrs[key]));
    return element;
  };
}
```

Test class that calls the utils
```
import { buildSubject, rerender } from "test/utils";
const subject = buildSubject("c-create-address-form", CreateAddressForm);
```

CreateAddressForm
```
import { LightningElement, api, track } from "lwc";
import { ShowToastEvent } from "lightning/platformShowToastEvent";
import createAddress from "@salesforce/apex/AddressController.createAddress";

export default class CreateAddressForm extends LightningElement {
  @api contactId;
  @track error;
  @track fieldErrors = [];
  @track generalErrors = [];
  @track isSaveDisabled = false;
  @track saveLabel = "Save";

  cancel() {
    this.dispatchEvent(new CustomEvent("cancel"));
  }

  saveClicked() {
    this.withModalDisabled(async () => this.performSave());
  }

  async withModalDisabled(performActivity) {
    this.disableModal();
    await performActivity();
    this.enableModal();
  }

  async performSave() {
    await this.clearErrors();

    const input = this.template.querySelector("c-user-address-input");
    if (!input.reportValidity()) {
      return;
    }

    const address = input.getValue();
    address.contactId = this.contactId;

    await createAddress({ userAddress: address })
      .then((response) => this.handleResponse(response))
      .catch((error) => this.handleFailure(error));
  }

  handleResponse({ data, errors }) {
    if (data && data.addressId) {
      this.saveSucceeded(data.addressId);
    } else {
      this.handleErrors(errors);
    }
  }

  saveSucceeded(_addressId) {
    this.fieldErrors = [];
    this.generalErrors = [];
    this.showToast();
    this.dispatchEvent(new CustomEvent("savesucceeded"));
  }

  handleFailure(_error) {
    this.handleErrors([{ message: "Something went wrong." }]);
  }

  handleErrors(errors) {
    this.fieldErrors = errors.filter((error) => !!error.field);
    this.generalErrors = errors.filter((error) => !error.field);
  }

  showToast() {
    const event = new ShowToastEvent({
      title: "Success",
      message: "Address was successfully created.",
      variant: "success"
    });
    this.dispatchEvent(event);
  }

  disableModal() {
    this.isSaveDisabled = true;
    this.saveLabel = "Saving";
  }

  enableModal() {
    this.isSaveDisabled = false;
    this.saveLabel = "Save";
  }

  async clearErrors() {
    this.fieldErrors = [];
    this.generalErrors = [];
    // Allow time to rerender
    return Promise.resolve();
  }
}

```

#### Expected Results
Test class passes

#### Actual Results
Error is shown
```
    TypeError: connector.connect is not a function

       5 |     const element = createElement(name, { is: constructor });
       6 |     Object.keys(attrs).forEach((key) => (element[key] = attrs[key]));
    >  7 |     document.body.appendChild(element);
         |     ^
       8 |     Object.keys(attrs)
       9 |       .filter((key) => key.startsWith("on"))
      10 |       .forEach((key) => element.addEventListener(key.substr(2), attrs[key]));

      at Array.<anonymous> (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:7477:19)
      at connectWireAdapters (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:7498:23)
      at runConnectedCallback (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:6927:5)
      at Object.insert (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:5330:7)
      at createChildrenHook (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:5104:15)
      at Object.insert (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:5254:5)
      at addVnodes (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:4712:15)
      at updateStaticChildren (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:4827:5)
      at node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:6834:9
      at runWithBoundaryProtection (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:7172:5)
      at patchShadowRoot (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:6826:7)
      at rehydrate (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:6810:5)
      at connectRootElement (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:6631:3)
      at callNodeSlot (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:7838:9)
      at HTMLBodyElement.document [as appendChild] (node_modules/@lwc/engine-dom/dist/engine-dom.cjs.js:7848:16)
      at subject (src/main/default/lwc/test/utils.js:7:5)
```

### Version

-   @salesforce/sfdx-lwc-jest: 1.0.1
-   Node: v.12.19.0

**Possible Solution**

**Additional context/Screenshots**

**Comment by pmdartus** [comment]
Thanks for raising this issue @gdlt88. 

Looking at the call stack, the LWC engine fails to connect the component because of an invalid wire adapter (see `connectWireAdapters` in the call stack). I find this quite suspicious as the component you shared doesn't have any reference to any wire adapter.

I am not able to reproduce this issue with the code you shared. For us to investigate further, could you share a small standalone repro (eg. a new SFDX project)?

**Comment by gdlt88** [comment]
@pmdartus thanks for your quick response. Do you know if a scratch-org built from the repo where we are facing this issue is enough for you? This is a private repo, and we might not be able to give you access and creating a small version of it might take us some time...

**Comment by pmdartus** [comment]
> Do you know if a scratch-org built from the repo where we are facing this issue is enough for you?

Unfortunately no because the test code is not published to the org.

**Comment by gdlt88** [comment]
Ok, let me see what I can do to create a smaller version of our repo where you can replicate the error

**Comment by gdlt88** [comment]
Ok found another class that might be using the wireAdapter and might give you more information to troubleshoot this while I try to find a way to create a smaller repo for you to test. See the code snippets below:

Test Class
```
import EditAddress from "c/editAddress";
import updateAddress from "@salesforce/apex/AddressController.updateAddress";
import canUpdate from "@salesforce/apex/AddressController.canUpdate";
import { registerLdsTestWireAdapter } from "@salesforce/wire-service-jest-util";
import { getRecord } from "lightning/uiRecordApi";
import "test/userAddressInput.wire";

import { buildSubject, rerender } from "test/utils";

const subject = buildSubject("c-edit-address", EditAddress);

const canUpdateAdapter = registerLdsTestWireAdapter(canUpdate);
const getAddressAdapter = registerLdsTestWireAdapter(getRecord);

jest.mock("@salesforce/apex/AddressController.updateAddress", () => ({ default: jest.fn() }), { virtual: true });

describe("c-edit-address", () => {
  beforeEach(() => {
    jest.resetAllMocks();
  });

  it("submits the contact user address", async () => {
    const element = subject({ addressId: 12356 });
    updateAddress.mockResolvedValue({});

    canUpdateAdapter.emit(true);
    await rerender();

    stubAddressInputValue(element, { address1: "the street" });

    await update(element);

    expect(updateAddress.mock.calls[0][0].id).toEqual(12356);
    expect(updateAddress.mock.calls[0][0].userAddress).toHaveProperty("address1", "the street");
  });

  it("renders field errors received from submission", async () => {
    const element = subject({ contactId: "theid" });
    updateAddress.mockResolvedValue({
      errors: [
        { field: "firstName", message: "must be set" },
        { message: "non-field error" },
        { field: "postalCode", message: "has an error" }
      ]
    });
    canUpdateAdapter.emit(true);
    await rerender();

    const addressInput = stubAddressInputValue(element, {});

    await update(element);

    expect(addressInput.errors).toIncludeSameMembers([
      { field: "postalCode", message: "has an error" },
      { field: "firstName", message: "must be set" }
    ]);
  });

  it("renders general errors received from submission", async () => {
    const element = subject({ contactId: "theid" });
    updateAddress.mockResolvedValue({
      errors: [
        { field: "firstName", message: "must be set" },
        { message: "non-field error" },
        { field: "postalCode", message: "has an error" },
        { message: "second error" }
      ]
    });
    canUpdateAdapter.emit(true);
    await rerender();

    stubAddressInputValue(element, {});

    await update(element);

    const errorPanel = element.shadowRoot.querySelector("c-error-panel");
    expect(errorPanel.errors).toIncludeSameMembers([{ message: "second error" }, { message: "non-field error" }]);
  });

  it("does not save if form is invalid", async () => {
    const element = subject();

    canUpdateAdapter.emit(true);
    await rerender();
    const addressInput = stubAddressInputValue(element, {});
    addressInput.reportValidity = () => false;

    await update(element);

    expect(updateAddress).not.toHaveBeenCalled();
  });

  it("clears all errors prior to validating input", async () => {
    const element = subject();
    updateAddress.mockResolvedValueOnce({ errors: [{ field: "firstName", message: "must be set" }] });
    updateAddress.mockResolvedValue({});
    canUpdateAdapter.emit(true);
    await rerender();
    const addressInput = stubAddressInputValue(element, {});

    await update(element);
    expect(addressInput.errors).not.toBeEmpty(); // Pre-assertion

    await update(element);

    expect(addressInput.errors).toBeEmpty();
  });

  it("renders loading message while loading", async () => {
    const element = subject();

    expect(byId(element, "loading")).not.toBeNull();

    canUpdateAdapter.emit(true);
    getAddressAdapter.emit({
      fields: {
        First_Name__c: { value: "" },
        Last_Name__c: { value: "" },
        Address_1__c: { value: "" },
        Address_2__c: { value: "" },
        City__c: { value: "" },
        State__c: { value: "" },
        Country__c: { value: "" },
        Postal_Code__c: { value: "" },
        Phone__c: { value: "" },
        Address_Type__c: { value: "" }
      }
    });

    await rerender();

    expect(byId(element, "loading")).toBeNull();
  });

  it("renders errors if address not fetched", async () => {
    const element = subject();

    expect(byId(element, "loading")).not.toBeNull();

    canUpdateAdapter.emit(true);
    getAddressAdapter.error({ message: "a loading error" });

    await rerender();

    expect(byId(element, "loading")).toBeNull();
    const errorPanel = element.shadowRoot.querySelector("c-error-panel");
    expect(errorPanel.errors).toIncludeSameMembers([{ message: "a loading error" }]);
  });
});

function stubAddressInputValue(element, value) {
  const addressInput = element.shadowRoot.querySelector("c-user-address-input");
  addressInput.reportValidity = () => true;
  addressInput.getValue = () => value;
  return addressInput;
}

async function update(element) {
  byId(element, "update").click();
  // Release the thread for multiple consecutive promises that occur during save
  await rerender();
  await rerender();
}

function byId(root, id) {
  return root.shadowRoot.querySelector(`[data-id='${id}']`);
}

```

Js component
```
import { LightningElement, api, track, wire } from "lwc";
import { getRecord } from "lightning/uiRecordApi";
import { ShowToastEvent } from "lightning/platformShowToastEvent";
import updateAddress from "@salesforce/apex/AddressController.updateAddress";
import canUpdate from "@salesforce/apex/AddressController.canUpdate";

export default class EditAddress extends LightningElement {
  @api addressId;
  @track error;
  @track fieldErrors = [];
  @track generalErrors = [];
  @track isPosting = false;
  @track updateLabel = "Update";
  @track address;
  @track isLoading = true;
  @track canUpdateAddress = true;
  @track addressType;
  @wire(getRecord, {
    recordId: "$addressId",
    fields: [
      "Address__c.First_Name__c",
      "Address__c.Last_Name__c",
      "Address__c.Address_1__c",
      "Address__c.Address_2__c",
      "Address__c.City__c",
      "Address__c.State__c",
      "Address__c.Country__c",
      "Address__c.Postal_Code__c",
      "Address__c.Phone__c",
      "Address__c.Address_Type__c"
    ]
  })
  wiredRecord({ error, data }) {
    // The reactive callback is streaming an empty object first (when the
    // component is mounted?) and a second value when the API call is
    // finished. Show the spinner until a valid response is received.
    if (!error && !data) {
      return;
    }

    if (error) {
      let message = "Unknown error";
      if (Array.isArray(error.body)) {
        message = error.body.map((e) => e.message).join(", ");
      } else if (typeof error.body.message === "string") {
        message = error.body.message;
      }
      this.handleErrors([{ message }]);
    } else if (data) {
      this.address = {
        firstName: data.fields.First_Name__c.value,
        lastName: data.fields.Last_Name__c.value,
        address1: data.fields.Address_1__c.value,
        address2: data.fields.Address_2__c.value,
        city: data.fields.City__c.value,
        state: data.fields.State__c.value,
        country: data.fields.Country__c.value,
        postalCode: data.fields.Postal_Code__c.value,
        phone: data.fields.Phone__c.value,
        addressType: data.fields.Address_Type__c.value
      };
      this.addressType = data.fields.Address_Type__c.value;
    }
  }

  @wire(canUpdate, { addressType: "$addressType" })
  canUpdateReceived({ data }) {
    this.isLoading = false;
    this.canUpdateAddress = data;
  }

  connectedCallback() {
    this.isLoading = true;
  }

  cancel() {
    this.dispatchEvent(new CustomEvent("cancel"));
  }

  updateClicked() {
    this.withModalDisabled(async () => this.performUpdate());
  }

  async withModalDisabled(performActivity) {
    this.disableModal();
    await performActivity();
    this.enableModal();
  }

  async performUpdate() {
    await this.clearErrors();

    const input = this.template.querySelector("c-user-address-input");
    if (!input.reportValidity()) {
      return;
    }

    const address = input.getValue();

    await updateAddress({ id: this.addressId, userAddress: address })
      .then((response) => this.handleResponse(response))
      .catch((error) => this.handleFailure(error));
  }

  handleResponse({ data, errors }) {
    if (data && data.addressId) {
      this.updateSucceeded(data.addressId);
    } else {
      this.handleErrors(errors);
    }
  }

  updateSucceeded(_addressId) {
    this.fieldErrors = [];
    this.generalErrors = [];
    this.showToast();
    this.dispatchEvent(new CustomEvent("updatesucceeded"));
  }

  handleFailure(_error) {
    this.handleErrors([{ message: "Something went wrong." }]);
  }

  handleErrors(errors) {
    this.fieldErrors = errors.filter((error) => !!error.field);
    this.generalErrors = errors.filter((error) => !error.field);
  }

  async clearErrors() {
    this.fieldErrors = [];
    this.generalErrors = [];
    // Allow time to rerender
    return Promise.resolve();
  }

  showToast() {
    const event = new ShowToastEvent({
      title: "Success",
      message: "Address was successfully updated.",
      variant: "success"
    });
    this.dispatchEvent(event);
  }

  disableModal() {
    this.isPosting = true;
    this.updateLabel = "Updating";
  }

  enableModal() {
    this.isPosting = false;
    this.updateLabel = "Update";
  }
}


This class is using the same utils I posted above and is facing the same issue
```

**Comment by gdlt88** [comment]
Any word on the code pasted above?

**Comment by pmdartus** [comment]
After looking at the example you shared above nothing jumps out. 

I will close this issue for now. Feel free to reopen the issue when you have a standalone repro for us to investigate further.

**Comment by gdlt88** [comment]
@vijayaditya1, this was a long time ago, but if I remember correctly, the issue was in the `jest.config.js`. In the module.exports of that file, we were doing something wrong. That may give you a place to start. I hope that this helps you to solve the issue
