### ISSUE TITLE
Tests using jest.mock failing after update to 0.8.0

### ISSUE THREAD

**Issue by pchittum** [salesforce/sfdx-lwc-jest#145]
### Description
In the sample apps (github.com/trailheadapps) we've updated our LWCs to API v49.0, along with our `sfdx-project.json`. We've also updated `sfdx-lwc-jest` to the pre-release version 0.8.0. No other changes have been made. 

In repos we've tested, any tests using `sfdx-lwc-jest` 0.8.0 and making use of `jest.mock` are now failing tests, with no other changes being made to the code base. 

You can see details in this test run: https://github.com/trailheadapps/lwc-recipes/pull/277/checks?check_run_id=685291669

#### Steps to Reproduce

- Clone github.com/trailheadapps/lwc-recipes. 
- Follow instructions for setting up project. 
- Fetch and switch to `pc/prerelease/project-upgrade` branch. 
- Run `npm run test:unit`

Test results show nine failed test suites. 

#### Expected Results

All tests run without failure.

#### Actual Results

```bash
 FAIL  force-app/main/default/lwc/apexImperativeMethodWithParams/__tests__/apexImperativeMethodWithParams.test.js
  ● Test suite failed to run

    Cannot find module '@jest/globals' from 'apexImperativeMethodWithParams.test.js'

      20 |         Name: 'Amy Taylor',
      21 |         Title: 'VP of Engineering',
    > 22 |         Phone: '4152568563',
         |       ^
      23 |         Email: 'amy@demo.net',
      24 |         Picture__c:
      25 |             'https://s3-us-west-1.amazonaws.com/sfdc-demo/people/amy_taylor.jpg'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at jest (force-app/main/default/lwc/apexImperativeMethodWithParams/__tests__/apexImperativeMethodWithParams.test.js:22:7)
      at Object.<anonymous> (force-app/main/default/lwc/apexImperativeMethodWithParams/__tests__/apexImperativeMethodWithParams.test.js:6:1)
```

### Version

-   @salesforce/sfdx-lwc-jest: 0.8.0
-   Node: 10.17.0

**Additional context/Screenshots**

This is a blocker for the current work to upgrade sample apps to Summer 20.

**Comment by ekashida** [comment]
W-7679855

**Comment by apapko** [comment]
@pchittum we have release v0.9.0, please give it a try

**Comment by pozil** [comment]
@apapko I confirm that v0.9.0 and v0.9.1 resolves the issue.
