### ISSUE TITLE
v0.10.1 possible regression: TypeError: adapterInstance.connect is not a function

### ISSUE THREAD

**Issue by msrivastav13** [salesforce/sfdx-lwc-jest#175]
### Description

We're seeing possible regressions after updating to v0.10.1. Our CI is reporting new [errors](https://github.com/trailheadapps/easy-spaces-lwc/pull/164/checks?check_run_id=1179358914).
I'm also able to reproduce locally.

#### Steps to Reproduce

`git clone git@github.com:trailheadapps/easy-spaces-lwc.git
git checkout mo/prerelease/api-version
cd easy-spaces-lwc
npm install
npm run test:unit`

####Expected Results

All tests pass (as before the sfdx-lwc-jest update).

### Actual Results
Tests are now failing due to internal errors like this one:

`**TypeError: adapterInstance.connect is not a function**

      35 | 
      36 |             element.market = MARKET_ID;
    > 37 |             document.body.appendChild(element);
         |             ^
      38 | 
      39 |             // Emit data from @wire
      40 |             getRelatedSpacesAdapter.emit(mockSpacesList);

      at Array.<anonymous> (node_modules/@lwc/engine/dist/engine.cjs.js:6702:63)
      at connectWireAdapters (node_modules/@lwc/engine/dist/engine.cjs.js:6713:23)
      at runConnectedCallback (node_modules/@lwc/engine/dist/engine.cjs.js:6162:5)
      at connectRootElement (node_modules/@lwc/engine/dist/engine.cjs.js:5907:3)
      at callNodeSlot (node_modules/@lwc/engine/dist/engine.cjs.js:7017:9)
      at HTMLBodyElement.document [as appendChild] (node_modules/@lwc/engine/dist/engine.cjs.js:7027:16)
      at Object.<anonymous> (es-space-mgmt/main/default/lwc/spaceDesignForm/__tests__/spaceDesignForm.test.js:37:13)`

As per @muenzpraeger, This is because it needs an update to lwc dependencies to the latest.

**Comment by pozil** [comment]
@jodarove could that issue be related to #172 ?

**Comment by jodarove** [comment]
@msrivastav13 @pozil i took a look to your issue, it turns out that [the project jest.config](https://github.com/trailheadapps/easy-spaces-lwc/blob/develop/jest.config.js) is overriding the `setupFilesAfterEnv` defined in [sfdx-lwc-jest](https://github.com/salesforce/sfdx-lwc-jest/blob/prerelease/src/config.js). You should merge your config with the one from sfdx-lwc-jest.

Here is a diff that will make the errors go away in easy-spaces-lwc:

```
Subject: [PATCH] fix: use sfdx-lwc-jest/config setupFilesAfterEnv

---
 jest.config.js | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/jest.config.js b/jest.config.js
index 3ca2db7..618069c 100644
--- a/jest.config.js
+++ b/jest.config.js
@@ -1,4 +1,8 @@
 const { jestConfig } = require('@salesforce/sfdx-lwc-jest/config');
+
+const setupFilesAfterEnv = jestConfig.setupFilesAfterEnv || [];
+setupFilesAfterEnv.push('<rootDir>/jest-sa11y-setup.js');
+
 module.exports = {
     ...jestConfig,
     // add any custom configurations here
@@ -12,5 +16,5 @@ module.exports = {
         '^lightning/platformShowToastEvent$':
             '<rootDir>/es-space-mgmt/test/jest-mocks/lightning/platformShowToastEvent'
     },
-    setupFilesAfterEnv: ['<rootDir>/jest-sa11y-setup.js']
+    setupFilesAfterEnv
 };
-- 
```

cc/ @pmdartus

**Comment by jodarove** [comment]
@pozil also notice that this is also present in [lwc-recipes](https://github.com/trailheadapps/lwc-recipes/blob/master/jest.config.js) and should be fixed in order to use v0.10.1 cc/ @albarivas

**Comment by msrivastav13** [comment]
@jodarove Thank you!! Will give a shot!!!

**Comment by msrivastav13** [comment]
This did actually fix the issue. We have many repos using this and we will update it. cc @albarivas @pozil

**Comment by pozil** [comment]
Thanks @jodarove.
